### PR TITLE
add support for nanosecond timestamps

### PR DESCRIPTION
**Pull request by lobeck**
- new feature of fluentd 0.14
- internally switches everything to EventTime
- no breaking change

### CODE REVIEW

**Comment by lobeck** [comment]
Found a bug in the EvenTime implementation, which i will fix. But there seem to be serious issues with the Buffer implementation. From what i've seen, it will throw a `BufferFullException` already at 50% but fixing seem to be difficult as the implementation is pretty weird.

**Comment by komamitsu** [comment]
@lobeck Thanks. This is a grate feature!

But I noticed this change doesn't work with Fluentd 0.12 and causes about 25% performance degradation with Fluentd 0.14. So we need to make this feature optional. I mean that users use Fluency without this feature by default, but users can enable this feature if they want to use.

For instance, the following option would work.
- When users call `emit(String tag, long timestamp, Map<String, Object> data)`, Fluency should work w/o EventTime as well as current behaviour.

Is it possible to update this pull request to do that?

**Comment by lobeck** [comment]
Already thought about that too, will take a look.

**Comment by komamitsu** [comment]
@lobeck If you don't have time for this, can I try to support the nanosecond timestamps feature?

**Comment by lobeck** [comment]
I'm sorry, but currently i can't continue to work on this. So feel free to take over or close this PR for now.

**Comment by komamitsu** [comment]
Don't say sorry 😸 
And thanks for letting me know about nanosecond timestamp

**Pull request closed without merging**
